typography_spectrum: 0.08858116250485182
content_rating:
  adult: false
color:
  brandStrength: 0.3001041910611093
  lightness: 0.7300947073381394
  saturation: 0.5562232912052423
  rhythmicContrast: 0.7280852717813104
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.9156367613468319
author:
  name: Bobby Hanson
  email: slapbass78@gmail.com
  url: bobbyhanson.com
logo: null
name: Bobby Hanson (Soundmaker)
navigation:
  - name: Sylvan Music
    url: sylvanmusic.com
    type: external
title: Enter the Sonic Hot Tub
